GRAPH: holograph
SEMANTIC_TRANSFER: 0.0
LEARNING_RATE: 0.2
DECAY_RATE: 0.001

CHUNK_THRESHOLD: null
EXEMPLAR_THRESHOLD: 0.3
BIND_OPERATION: addition
GENERALIZE: false

FTP_PREFERENCE: 1
CHUNK_LEARNING: .2
MEMORY_SIZE: 4

DIM: 10000
PERCENT_NON_ZERO: 0.005
BIND: false

ADD_BOUNDARIES: false