PARSE: greedy
LEARNING_RATE: 0.1
DEPTH: 0
DECAY: false
EXEMPLAR_THRESHOLD: 0.2
CHUNK_THRESHOLD: null
FTP_PREFERENCE: 1
CHUNK_LEARNING: 0.0
MEMORY_SIZE: 4
ADD_BOUNDARIES: false

HIERARCHICAL: true
GENERALIZE: false
DYNAMIC: null
COMPOSITION: false

GRAPH: holograph
DIM: 10000
PERCENT_NON_ZERO: 0.005
BIND: false
BIND_OPERATION: addition
