GRAPH: holograph
SEMANTIC_TRANSFER: 0.0
LEARNING_RATE: 0.1
LEARN_MODE: old
DEPTH: 0
DECAY: false

CHUNK_THRESHOLD: null
EXEMPLAR_THRESHOLD: 0.2
BIND_OPERATION: addition
GENERALIZE: false
DYNAMIC: null
COMPOSITION: false
COMP2: false

FTP_PREFERENCE: 1
CHUNK_LEARNING: 0.0
MEMORY_SIZE: 4

DIM: 10000
PERCENT_NON_ZERO: 0.005
BIND: false

ADD_BOUNDARIES: false