PARSE: greedy
LEARNING_RATE: 0.2
DEPTH: 0
DECAY: false
EXEMPLAR_THRESHOLD: 0.3
CHUNK_THRESHOLD: null
BTP_PREFERENCE: 1
CHUNK_LEARNING: 0.0
MEMORY_SIZE: 4
ADD_BOUNDARIES: true
SPEAK: markov

HIERARCHICAL: true
GENERALIZE: false
DYNAMIC: null
COMPOSITION: false

GRAPH: holograph
DIM: 10000
PERCENT_NON_ZERO: 0.005
BIND_OPERATION: addition
INITIAL_ROW: 4
