PARSE: greedy
LEARNING_RATE: 0.2
DEPTH: 0
DECAY: false
CHUNK_THRESHOLD: 0.3
BTP_PREFERENCE: 1
MEMORY_SIZE: 4
ADD_BOUNDARIES: true
SPEAK: markov

HIERARCHICAL: true
GENERALIZE: false
DYNAMIC: null
COMPOSITION: false

GRAPH: holograph
DIM: 10000
PERCENT_NON_ZERO: 0.005
BIND_OPERATION: addition
INITIAL_ROW: 2
